import type { BillingCustomerLocale, BillingLocaleCatalog } from './billing-copy-locale.js';
import { billingLocaleText, formatBillingCopy, type BillingCopyPluralForms } from './billing-copy-locale.js';

export type BillingSubscriptionCopy = Readonly<{
  upgradeAction: string;
  upgradeDescription: string;
  activeSubscription: string;
  onlyManagerUpgrade: string;
  upgradeUnavailable: string;
  managePaymentAction: string;
  portalDescription: string;
  onlyManagerPayment: string;
  portalUnavailable: string;
  cancelSubscriptionAction: string;
  cancelDescription: string;
  cancellationAlreadyScheduled: string;
  onlyManagerCancel: string;
  noCancellableSubscription: string;
  monthlySubscription: string;
  tariffDetails: string;
  monthlyAdjustment: string;
  oneTimeAdjustment: string;
  organisationTitle: string;
  organisationDescription: string;
  organisationFallback: string;
  organisationManagerMessage: string;
  organisationMemberMessage: string;
  previewTitle: string;
  chooseCancellation: string;
  currentOnlyLabel: string;
  keepOtherProducts: string;
  cancelRelatedLabel: string;
  alsoCancelProducts: string;
  thisSubscriptionEnds: string;
  noSeparateSubscription: string;
  confirmCancellation: string;
  cancellationScheduled: string;
  oneSubscriptionEnds: string;
  manySubscriptionsEnd: BillingCopyPluralForms;
  noSeparateSubscriptionCanceled: string;
}>;

export const BILLING_SUBSCRIPTION_COPY = {
  cs: {
    upgradeAction: 'Změnit tarif',
    upgradeDescription: 'Vyberte tarif a zaplaťte za službu přes zabezpečenou platební stránku.',
    activeSubscription: 'Předplatné už je aktivní.',
    onlyManagerUpgrade: 'Tarif může změnit pouze správce plateb.',
    upgradeUnavailable: 'Online platba pro tento tarif není dostupná.',
    managePaymentAction: 'Spravovat platby',
    portalDescription: 'Otevřít zabezpečený portál pro správu plateb.',
    onlyManagerPayment: 'Platby může spravovat pouze správce plateb.',
    portalUnavailable: 'Aktivní předplatné nelze spravovat.',
    cancelSubscriptionAction: 'Zrušit předplatné',
    cancelDescription: 'Před potvrzením zobrazit, kterých služeb se zrušení týká.',
    cancellationAlreadyScheduled: 'Zrušení už je naplánováno.',
    onlyManagerCancel: 'Předplatné může zrušit pouze správce plateb.',
    noCancellableSubscription: 'Není aktivní předplatné, které lze zrušit.',
    monthlySubscription: 'měsíční předplatné',
    tariffDetails: 'Součást vašeho aktuálního tarifu.',
    monthlyAdjustment: 'Měsíční úprava',
    oneTimeAdjustment: 'Jednorázová úprava',
    organisationTitle: 'Firemní fakturace',
    organisationDescription: 'Fakturace zahrnuje všechny týmy organizace.',
    organisationFallback: 'vaše organizace',
    organisationManagerMessage: 'Fakturaci tohoto týmu spravuje {organisation}. Otevřete firemní fakturaci a zobrazte útratu, kredity, platební metodu a faktury všech týmů.',
    organisationMemberMessage: 'Fakturaci tohoto týmu spravuje {organisation}. Správce firemních plateb se stará o útratu, kredity a platby.',
    previewTitle: 'Zrušit předplatné služby {name}?',
    chooseCancellation: 'Vyberte, zda chcete zrušit jen tuto službu, nebo také další služby, které tým používá přímo.',
    currentOnlyLabel: 'Zrušit pouze službu {name}',
    keepOtherProducts: 'Ostatní přímá předplatná týmu zůstanou aktivní.',
    cancelRelatedLabel: 'Zrušit všechna související přímá předplatná',
    alsoCancelProducts: 'Zrušit také: {products}.',
    thisSubscriptionEnds: 'Toto předplatné skončí na konci aktuálního období.',
    noSeparateSubscription: 'Nepřímo používané služby nemají samostatné předplatné ke zrušení.',
    confirmCancellation: 'Potvrdit zrušení',
    cancellationScheduled: 'Zrušení je naplánováno',
    oneSubscriptionEnds: '1 přímé předplatné skončí na konci aktuálního období.',
    manySubscriptionsEnd: { one: '{count} přímé předplatné skončí na konci aktuálního období.', few: '{count} přímá předplatná skončí na konci aktuálního období.', other: '{count} přímých předplatných skončí na konci aktuálního období.' },
    noSeparateSubscriptionCanceled: 'Žádné samostatné předplatné nebylo zrušeno.',
  },
  'en-US': {
    upgradeAction: 'Change plan',
    upgradeDescription: 'Choose a plan and pay securely for this product.',
    activeSubscription: 'A subscription is already active.',
    onlyManagerUpgrade: 'Only a billing manager can change the plan.',
    upgradeUnavailable: 'Online payment is not available for this plan.',
    managePaymentAction: 'Manage payment',
    portalDescription: 'Open the secure payment portal.',
    onlyManagerPayment: 'Only a billing manager can manage payment.',
    portalUnavailable: 'There is no active subscription to manage.',
    cancelSubscriptionAction: 'Cancel subscription',
    cancelDescription: 'Preview the products affected before confirming cancellation.',
    cancellationAlreadyScheduled: 'Cancellation is already scheduled.',
    onlyManagerCancel: 'Only a billing manager can cancel the subscription.',
    noCancellableSubscription: 'There is no active subscription to cancel.',
    monthlySubscription: 'Monthly subscription',
    tariffDetails: 'Included in your current plan.',
    monthlyAdjustment: 'Monthly adjustment',
    oneTimeAdjustment: 'One-time adjustment',
    organisationTitle: 'Organization billing',
    organisationDescription: 'Billing covers every team in {organisation}.',
    organisationFallback: 'your organization',
    organisationManagerMessage: 'Billing for this team is managed by {organisation}. Open organization billing to see spend, credits, payment method, and invoices for every team.',
    organisationMemberMessage: 'Billing for this team is managed by {organisation}. An organization billing manager looks after spend, credits, and payment.',
    previewTitle: 'Cancel {name}?',
    chooseCancellation: 'Choose whether to cancel only this product or every related product your team subscribes to directly.',
    currentOnlyLabel: 'Cancel {name} only',
    keepOtherProducts: 'Keep your team’s other direct product subscriptions active.',
    cancelRelatedLabel: 'Cancel all related direct subscriptions',
    alsoCancelProducts: 'Also cancel: {products}.',
    thisSubscriptionEnds: 'This subscription will end at the end of its current billing period.',
    noSeparateSubscription: 'Indirectly used products do not have a separate subscription to cancel.',
    confirmCancellation: 'Confirm cancellation',
    cancellationScheduled: 'Cancellation scheduled',
    oneSubscriptionEnds: 'The subscription will end at the end of its current billing period.',
    manySubscriptionsEnd: { one: '{count} direct subscription will end at the end of its current billing period.', other: '{count} direct subscriptions will end at the end of their current billing periods.' },
    noSeparateSubscriptionCanceled: 'No separate subscription was canceled.',
  },
  'en-GB': {
    upgradeAction: 'Change plan',
    upgradeDescription: 'Choose a plan and pay securely for this product.',
    activeSubscription: 'A subscription is already active.',
    onlyManagerUpgrade: 'Only a billing manager can change the plan.',
    upgradeUnavailable: 'Online payment is not available for this plan.',
    managePaymentAction: 'Manage payment',
    portalDescription: 'Open the secure payment portal.',
    onlyManagerPayment: 'Only a billing manager can manage payment.',
    portalUnavailable: 'There is no active subscription to manage.',
    cancelSubscriptionAction: 'Cancel subscription',
    cancelDescription: 'Preview the products affected before confirming cancellation.',
    cancellationAlreadyScheduled: 'Cancellation is already scheduled.',
    onlyManagerCancel: 'Only a billing manager can cancel the subscription.',
    noCancellableSubscription: 'There is no active subscription to cancel.',
    monthlySubscription: 'Monthly subscription',
    tariffDetails: 'Included in your current plan.',
    monthlyAdjustment: 'Monthly adjustment',
    oneTimeAdjustment: 'One-time adjustment',
    organisationTitle: 'Organisation billing',
    organisationDescription: 'Billing covers every team in {organisation}.',
    organisationFallback: 'your organisation',
    organisationManagerMessage: 'Billing for this team is managed by {organisation}. Open organisation billing to see spend, credits, payment method, and invoices for every team.',
    organisationMemberMessage: 'Billing for this team is managed by {organisation}. An organisation billing manager looks after spend, credits, and payment.',
    previewTitle: 'Cancel {name}?',
    chooseCancellation: 'Choose whether to cancel only this product or every related product your team subscribes to directly.',
    currentOnlyLabel: 'Cancel {name} only',
    keepOtherProducts: 'Keep your team’s other direct product subscriptions active.',
    cancelRelatedLabel: 'Cancel all related direct subscriptions',
    alsoCancelProducts: 'Also cancel: {products}.',
    thisSubscriptionEnds: 'This subscription will end at the end of its current billing period.',
    noSeparateSubscription: 'Indirectly used products do not have a separate subscription to cancel.',
    confirmCancellation: 'Confirm cancellation',
    cancellationScheduled: 'Cancellation scheduled',
    oneSubscriptionEnds: 'The subscription will end at the end of its current billing period.',
    manySubscriptionsEnd: { one: '{count} direct subscription will end at the end of its current billing period.', other: '{count} direct subscriptions will end at the end of their current billing periods.' },
    noSeparateSubscriptionCanceled: 'No separate subscription was cancelled.',
  },
  de: {
    upgradeAction: 'Tarif ändern',
    upgradeDescription: 'Wählen Sie einen Tarif und bezahlen Sie sicher für dieses Produkt.',
    activeSubscription: 'Ein Abonnement ist bereits aktiv.',
    onlyManagerUpgrade: 'Nur ein Abrechnungsmanager kann den Tarif ändern.',
    upgradeUnavailable: 'Onlinezahlungen sind für diesen Tarif nicht verfügbar.',
    managePaymentAction: 'Zahlung verwalten',
    portalDescription: 'Das sichere Zahlungsportal öffnen.',
    onlyManagerPayment: 'Nur ein Abrechnungsmanager kann Zahlungen verwalten.',
    portalUnavailable: 'Es gibt kein aktives verwaltbares Abonnement.',
    cancelSubscriptionAction: 'Abonnement kündigen',
    cancelDescription: 'Prüfen Sie vor der Bestätigung, welche Produkte betroffen sind.',
    cancellationAlreadyScheduled: 'Die Kündigung ist bereits vorgemerkt.',
    onlyManagerCancel: 'Nur ein Abrechnungsmanager kann das Abonnement kündigen.',
    noCancellableSubscription: 'Es gibt kein aktives kündbares Abonnement.',
    monthlySubscription: 'Monatliches Abonnement',
    tariffDetails: 'In Ihrem aktuellen Tarif enthalten.',
    monthlyAdjustment: 'Monatliche Anpassung',
    oneTimeAdjustment: 'Einmalige Anpassung',
    organisationTitle: 'Organisationsabrechnung',
    organisationDescription: 'Die Abrechnung umfasst alle Teams von {organisation}.',
    organisationFallback: 'Ihre Organisation',
    organisationManagerMessage: 'Die Abrechnung dieses Teams wird von {organisation} verwaltet. Öffnen Sie die Organisationsabrechnung, um Ausgaben, Credits, Zahlungsmethoden und Rechnungen aller Teams zu sehen.',
    organisationMemberMessage: 'Die Abrechnung dieses Teams wird von {organisation} verwaltet. Ein Abrechnungsmanager der Organisation kümmert sich um Ausgaben, Credits und Zahlungen.',
    previewTitle: '{name} kündigen?',
    chooseCancellation: 'Wählen Sie, ob Sie nur dieses Produkt oder alle zugehörigen direkt abonnierten Teamprodukte kündigen möchten.',
    currentOnlyLabel: 'Nur {name} kündigen',
    keepOtherProducts: 'Die anderen direkten Produktabonnements Ihres Teams bleiben aktiv.',
    cancelRelatedLabel: 'Alle zugehörigen direkten Abonnements kündigen',
    alsoCancelProducts: 'Ebenfalls kündigen: {products}.',
    thisSubscriptionEnds: 'Dieses Abonnement endet zum Ende des aktuellen Abrechnungszeitraums.',
    noSeparateSubscription: 'Indirekt genutzte Produkte haben kein separates kündbares Abonnement.',
    confirmCancellation: 'Kündigung bestätigen',
    cancellationScheduled: 'Kündigung vorgemerkt',
    oneSubscriptionEnds: 'Das Abonnement endet zum Ende des aktuellen Abrechnungszeitraums.',
    manySubscriptionsEnd: { one: '{count} direktes Abonnement endet zum Ende des aktuellen Abrechnungszeitraums.', other: '{count} direkte Abonnements enden zum Ende des aktuellen Abrechnungszeitraums.' },
    noSeparateSubscriptionCanceled: 'Es wurde kein separates Abonnement gekündigt.',
  },
  es: {
    upgradeAction: 'Cambiar plan',
    upgradeDescription: 'Elige un plan y paga este producto en una página de pago segura.',
    activeSubscription: 'Ya hay una suscripción activa.',
    onlyManagerUpgrade: 'Solo un gestor de facturación puede cambiar el plan.',
    upgradeUnavailable: 'El pago en línea no está disponible para este plan.',
    managePaymentAction: 'Gestionar pago',
    portalDescription: 'Abrir el portal seguro de pagos.',
    onlyManagerPayment: 'Solo un gestor de facturación puede gestionar el pago.',
    portalUnavailable: 'No hay una suscripción activa que se pueda gestionar.',
    cancelSubscriptionAction: 'Cancelar suscripción',
    cancelDescription: 'Consulta los productos afectados antes de confirmar la cancelación.',
    cancellationAlreadyScheduled: 'La cancelación ya está programada.',
    onlyManagerCancel: 'Solo un gestor de facturación puede cancelar la suscripción.',
    noCancellableSubscription: 'No hay una suscripción activa que se pueda cancelar.',
    monthlySubscription: 'Suscripción mensual',
    tariffDetails: 'Incluido en tu plan actual.',
    monthlyAdjustment: 'Ajuste mensual',
    oneTimeAdjustment: 'Ajuste único',
    organisationTitle: 'Facturación de la organización',
    organisationDescription: 'La facturación incluye todos los equipos de {organisation}.',
    organisationFallback: 'tu organización',
    organisationManagerMessage: 'La facturación de este equipo la gestiona {organisation}. Abre la facturación de la organización para ver el gasto, los créditos, el método de pago y las facturas de todos los equipos.',
    organisationMemberMessage: 'La facturación de este equipo la gestiona {organisation}. Un gestor de facturación de la organización se ocupa del gasto, los créditos y los pagos.',
    previewTitle: '¿Cancelar {name}?',
    chooseCancellation: 'Elige si quieres cancelar solo este producto o todos los productos relacionados a los que tu equipo está suscrito directamente.',
    currentOnlyLabel: 'Cancelar solo {name}',
    keepOtherProducts: 'Las demás suscripciones directas de productos del equipo seguirán activas.',
    cancelRelatedLabel: 'Cancelar todas las suscripciones directas relacionadas',
    alsoCancelProducts: 'Cancelar también: {products}.',
    thisSubscriptionEnds: 'Esta suscripción terminará al final del periodo de facturación actual.',
    noSeparateSubscription: 'Los productos de uso indirecto no tienen una suscripción independiente que cancelar.',
    confirmCancellation: 'Confirmar cancelación',
    cancellationScheduled: 'Cancelación programada',
    oneSubscriptionEnds: 'La suscripción terminará al final del periodo de facturación actual.',
    manySubscriptionsEnd: { one: '{count} suscripción directa terminará al final del periodo de facturación actual.', other: '{count} suscripciones directas terminarán al final de sus periodos de facturación actuales.' },
    noSeparateSubscriptionCanceled: 'No se canceló ninguna suscripción independiente.',
  },
  fr: {
    upgradeAction: 'Changer d’offre',
    upgradeDescription: 'Choisissez une offre et payez ce produit sur une page sécurisée.',
    activeSubscription: 'Un abonnement est déjà actif.',
    onlyManagerUpgrade: 'Seul un responsable de la facturation peut changer d’offre.',
    upgradeUnavailable: 'Le paiement en ligne n’est pas disponible pour cette offre.',
    managePaymentAction: 'Gérer le paiement',
    portalDescription: 'Ouvrir le portail de paiement sécurisé.',
    onlyManagerPayment: 'Seul un responsable de la facturation peut gérer le paiement.',
    portalUnavailable: 'Aucun abonnement actif ne peut être géré.',
    cancelSubscriptionAction: 'Résilier l’abonnement',
    cancelDescription: 'Consultez les produits concernés avant de confirmer la résiliation.',
    cancellationAlreadyScheduled: 'La résiliation est déjà programmée.',
    onlyManagerCancel: 'Seul un responsable de la facturation peut résilier l’abonnement.',
    noCancellableSubscription: 'Aucun abonnement actif ne peut être résilié.',
    monthlySubscription: 'Abonnement mensuel',
    tariffDetails: 'Inclus dans votre offre actuelle.',
    monthlyAdjustment: 'Ajustement mensuel',
    oneTimeAdjustment: 'Ajustement ponctuel',
    organisationTitle: 'Facturation de l’organisation',
    organisationDescription: 'La facturation couvre toutes les équipes de {organisation}.',
    organisationFallback: 'votre organisation',
    organisationManagerMessage: 'La facturation de cette équipe est gérée par {organisation}. Ouvrez la facturation de l’organisation pour consulter les dépenses, crédits, moyens de paiement et factures de chaque équipe.',
    organisationMemberMessage: 'La facturation de cette équipe est gérée par {organisation}. Un responsable de la facturation de l’organisation s’occupe des dépenses, crédits et paiements.',
    previewTitle: 'Résilier {name} ?',
    chooseCancellation: 'Choisissez de résilier uniquement ce produit ou tous les produits associés auxquels votre équipe est directement abonnée.',
    currentOnlyLabel: 'Résilier uniquement {name}',
    keepOtherProducts: 'Les autres abonnements directs de votre équipe resteront actifs.',
    cancelRelatedLabel: 'Résilier tous les abonnements directs associés',
    alsoCancelProducts: 'Résilier aussi : {products}.',
    thisSubscriptionEnds: 'Cet abonnement prendra fin à la fin de la période de facturation en cours.',
    noSeparateSubscription: 'Les produits utilisés indirectement n’ont pas d’abonnement distinct à résilier.',
    confirmCancellation: 'Confirmer la résiliation',
    cancellationScheduled: 'Résiliation programmée',
    oneSubscriptionEnds: 'L’abonnement prendra fin à la fin de la période de facturation en cours.',
    manySubscriptionsEnd: { one: '{count} abonnement direct prendra fin à la fin de sa période de facturation en cours.', other: '{count} abonnements directs prendront fin à la fin de leur période de facturation en cours.' },
    noSeparateSubscriptionCanceled: 'Aucun abonnement distinct n’a été résilié.',
  },
  it: {
    upgradeAction: 'Cambia piano',
    upgradeDescription: 'Scegli un piano e paga questo prodotto tramite una pagina sicura.',
    activeSubscription: 'È già attivo un abbonamento.',
    onlyManagerUpgrade: 'Solo un responsabile della fatturazione può cambiare piano.',
    upgradeUnavailable: 'Il pagamento online non è disponibile per questo piano.',
    managePaymentAction: 'Gestisci pagamento',
    portalDescription: 'Apri il portale sicuro dei pagamenti.',
    onlyManagerPayment: 'Solo un responsabile della fatturazione può gestire i pagamenti.',
    portalUnavailable: 'Non è attivo alcun abbonamento da gestire.',
    cancelSubscriptionAction: 'Annulla abbonamento',
    cancelDescription: 'Controlla i prodotti interessati prima di confermare l’annullamento.',
    cancellationAlreadyScheduled: 'L’annullamento è già programmato.',
    onlyManagerCancel: 'Solo un responsabile della fatturazione può annullare l’abbonamento.',
    noCancellableSubscription: 'Non è attivo alcun abbonamento da annullare.',
    monthlySubscription: 'Abbonamento mensile',
    tariffDetails: 'Incluso nel tuo piano attuale.',
    monthlyAdjustment: 'Rettifica mensile',
    oneTimeAdjustment: 'Rettifica singola',
    organisationTitle: 'Fatturazione dell’organizzazione',
    organisationDescription: 'La fatturazione include tutti i team di {organisation}.',
    organisationFallback: 'la tua organizzazione',
    organisationManagerMessage: 'La fatturazione di questo team è gestita da {organisation}. Apri la fatturazione dell’organizzazione per vedere spese, crediti, metodi di pagamento e fatture di tutti i team.',
    organisationMemberMessage: 'La fatturazione di questo team è gestita da {organisation}. Un responsabile della fatturazione dell’organizzazione si occupa di spese, crediti e pagamenti.',
    previewTitle: 'Annullare {name}?',
    chooseCancellation: 'Scegli se annullare solo questo prodotto o tutti i prodotti correlati a cui il team è abbonato direttamente.',
    currentOnlyLabel: 'Annulla solo {name}',
    keepOtherProducts: 'Gli altri abbonamenti diretti del team resteranno attivi.',
    cancelRelatedLabel: 'Annulla tutti gli abbonamenti diretti correlati',
    alsoCancelProducts: 'Annulla anche: {products}.',
    thisSubscriptionEnds: 'L’abbonamento terminerà alla fine del periodo di fatturazione corrente.',
    noSeparateSubscription: 'I prodotti usati indirettamente non hanno un abbonamento separato da annullare.',
    confirmCancellation: 'Conferma annullamento',
    cancellationScheduled: 'Annullamento programmato',
    oneSubscriptionEnds: 'L’abbonamento terminerà alla fine del periodo di fatturazione corrente.',
    manySubscriptionsEnd: { one: '{count} abbonamento diretto terminerà alla fine del periodo di fatturazione corrente.', other: '{count} abbonamenti diretti termineranno alla fine dei rispettivi periodi di fatturazione correnti.' },
    noSeparateSubscriptionCanceled: 'Nessun abbonamento separato è stato annullato.',
  },
} satisfies BillingLocaleCatalog<BillingSubscriptionCopy>;

export function billingSubscriptionCopy(locale?: BillingCustomerLocale): BillingSubscriptionCopy {
  return billingLocaleText(BILLING_SUBSCRIPTION_COPY, locale);
}

export function billingSubscriptionText(
  text: string,
  values: Readonly<Record<string, string | number>>,
): string {
  return formatBillingCopy(text, values);
}
