import type { BillingCustomerLocale, BillingLocaleCatalog } from './billing-copy-locale.js';
import { billingLocaleText } from './billing-copy-locale.js';

export type BillingCreditAutoTopUpCopy = Readonly<{
  status: Readonly<Record<'disabled' | 'active' | 'paused' | 'requires_action' | 'needs_review', string>>;
  activeDescription: string;
  disabledDescription: string;
  pausedForCapDescription: string;
  pausedForCapNoResetDescription: string;
  optionLabel: string;
  optionDescription: string;
  setupAction: string;
  setupDescription: string;
  setupUnavailable: string;
  updateAction: string;
  updateDescription: string;
  updateUnavailable: string;
  consentDescription: string;
  disableAction: string;
  disableDescription: string;
  disableUnavailable: string;
  changeCardAction: string;
  reviewPaymentAction: string;
  recoveryDescription: string;
  recoveryUnavailable: string;
  noSavedPaymentMethod: string;
  savedPaymentMethod: string;
  cardFallback: string;
  cardEnding: string;
  consentedByFallback: string;
}>;

export const BILLING_CREDIT_AUTO_TOP_UP_COPY = {
  cs: {
    status: { disabled: 'Vypnuto', active: 'Zapnuto', paused: 'Pozastaveno', requires_action: 'Je potřeba potvrdit platbu', needs_review: 'Čeká na ověření' },
    activeDescription: 'Použijí se uložený limit zůstatku, částka dobití a měsíční limit.',
    disabledDescription: 'Automatické dobíjení je pro tento tým vypnuté.',
    pausedForCapDescription: 'Měsíční limit nestačí na další dobití. Obnoví se {date}.',
    pausedForCapNoResetDescription: 'Měsíční limit nestačí na další dobití.',
    optionLabel: 'Dobít {refill}, když zůstatek klesne pod {threshold}',
    optionDescription: 'Tato volba určuje hranici, částku dobití a měsíční limit.',
    setupAction: 'Nastavit automatické dobíjení',
    setupDescription: 'Před zapnutím zkontrolujte a potvrďte tyto podmínky.',
    setupUnavailable: 'Vyberte dostupnou možnost a uložte platební kartu.',
    updateAction: 'Použít tuto možnost dobíjení',
    updateDescription: 'Změnit hranici zůstatku, částku dobití a měsíční limit.',
    updateUnavailable: 'Možnost teď nelze změnit. Zkontrolujte platební kartu a souhlas.',
    consentDescription: 'Souhlas platí pro uloženou hranici zůstatku, částku dobití a měsíční limit.',
    disableAction: 'Vypnout automatické dobíjení',
    disableDescription: 'Zastavit budoucí automatické platby. Dostupné kredity zůstanou beze změny.',
    disableUnavailable: 'Automatické dobíjení teď nelze vypnout.',
    changeCardAction: 'Změnit kartu',
    reviewPaymentAction: 'Zkontrolovat platbu',
    recoveryDescription: 'Otevřete zabezpečenou stránku a zkontrolujte platbu nebo kartu.',
    recoveryUnavailable: 'Tuto akci teď nelze použít.',
    noSavedPaymentMethod: 'Není uložena žádná platební metoda',
    savedPaymentMethod: 'Uložená platební metoda',
    cardFallback: 'Karta',
    cardEnding: ' končící na {last4}',
    consentedByFallback: 'Člen týmu',
  },
  'en-US': {
    status: { disabled: 'Off', active: 'On', paused: 'Paused', requires_action: 'Payment needs attention', needs_review: 'Under review' },
    activeDescription: 'The saved balance threshold, refill amount, and monthly limit apply.',
    disabledDescription: 'Automatic top-up is off for this team.',
    pausedForCapDescription: 'The monthly limit cannot cover another refill. It resets on {date}.',
    pausedForCapNoResetDescription: 'The monthly limit cannot cover another refill right now.',
    optionLabel: 'Add {refill} when the balance falls below {threshold}',
    optionDescription: 'This option sets the balance threshold, refill amount, and monthly limit.',
    setupAction: 'Set up automatic top-up',
    setupDescription: 'Review and confirm these terms before turning it on.',
    setupUnavailable: 'Choose an available option and save a payment method first.',
    updateAction: 'Use this top-up option',
    updateDescription: 'Change the balance threshold, refill amount, and monthly limit.',
    updateUnavailable: 'This option cannot be changed right now. Check the payment method and consent.',
    consentDescription: 'Your consent covers the saved balance threshold, refill amount, and monthly limit.',
    disableAction: 'Turn off automatic top-up',
    disableDescription: 'Stop future automatic charges. Your available credits will not change.',
    disableUnavailable: 'Automatic top-up cannot be turned off right now.',
    changeCardAction: 'Change card',
    reviewPaymentAction: 'Review payment',
    recoveryDescription: 'Open the secure payment page to review your payment or card.',
    recoveryUnavailable: 'This action is unavailable right now.',
    noSavedPaymentMethod: 'No payment method saved',
    savedPaymentMethod: 'Saved payment method',
    cardFallback: 'Card',
    cardEnding: ' ending in {last4}',
    consentedByFallback: 'Team member',
  },
  'en-GB': {
    status: { disabled: 'Off', active: 'On', paused: 'Paused', requires_action: 'Payment needs attention', needs_review: 'Under review' },
    activeDescription: 'The saved balance threshold, refill amount, and monthly limit apply.',
    disabledDescription: 'Automatic top-up is off for this team.',
    pausedForCapDescription: 'The monthly limit cannot cover another refill. It resets on {date}.',
    pausedForCapNoResetDescription: 'The monthly limit cannot cover another refill right now.',
    optionLabel: 'Add {refill} when the balance falls below {threshold}',
    optionDescription: 'This option sets the balance threshold, refill amount, and monthly limit.',
    setupAction: 'Set up automatic top-up',
    setupDescription: 'Review and confirm these terms before turning it on.',
    setupUnavailable: 'Choose an available option and save a payment method first.',
    updateAction: 'Use this top-up option',
    updateDescription: 'Change the balance threshold, refill amount, and monthly limit.',
    updateUnavailable: 'This option cannot be changed right now. Check the payment method and consent.',
    consentDescription: 'Your consent covers the saved balance threshold, refill amount, and monthly limit.',
    disableAction: 'Turn off automatic top-up',
    disableDescription: 'Stop future automatic charges. Your available credits will not change.',
    disableUnavailable: 'Automatic top-up cannot be turned off right now.',
    changeCardAction: 'Change card',
    reviewPaymentAction: 'Review payment',
    recoveryDescription: 'Open the secure payment page to review your payment or card.',
    recoveryUnavailable: 'This action is unavailable right now.',
    noSavedPaymentMethod: 'No payment method saved',
    savedPaymentMethod: 'Saved payment method',
    cardFallback: 'Card',
    cardEnding: ' ending in {last4}',
    consentedByFallback: 'Team member',
  },
  de: {
    status: { disabled: 'Aus', active: 'An', paused: 'Pausiert', requires_action: 'Zahlung erfordert Aufmerksamkeit', needs_review: 'Wird geprüft' },
    activeDescription: 'Es gelten der gespeicherte Kontostand, der Aufladebetrag und das Monatslimit.',
    disabledDescription: 'Automatische Aufladungen sind für dieses Team ausgeschaltet.',
    pausedForCapDescription: 'Das Monatslimit reicht nicht für eine weitere Aufladung. Es wird am {date} zurückgesetzt.',
    pausedForCapNoResetDescription: 'Das Monatslimit reicht derzeit nicht für eine weitere Aufladung.',
    optionLabel: '{refill} aufladen, wenn das Guthaben unter {threshold} fällt',
    optionDescription: 'Diese Option legt den Kontostand, den Aufladebetrag und das Monatslimit fest.',
    setupAction: 'Automatische Aufladungen einrichten',
    setupDescription: 'Prüfen und bestätigen Sie diese Bedingungen, bevor Sie die Funktion einschalten.',
    setupUnavailable: 'Wählen Sie eine verfügbare Option und speichern Sie zuerst eine Zahlungsmethode.',
    updateAction: 'Diese Aufladeoption verwenden',
    updateDescription: 'Kontostand, Aufladebetrag und Monatslimit ändern.',
    updateUnavailable: 'Diese Option kann gerade nicht geändert werden. Prüfen Sie Zahlungsmethode und Zustimmung.',
    consentDescription: 'Ihre Zustimmung gilt für Kontostand, Aufladebetrag und Monatslimit.',
    disableAction: 'Automatische Aufladungen ausschalten',
    disableDescription: 'Künftige automatische Abbuchungen stoppen. Ihr verfügbares Guthaben bleibt unverändert.',
    disableUnavailable: 'Automatische Aufladungen können gerade nicht ausgeschaltet werden.',
    changeCardAction: 'Karte ändern',
    reviewPaymentAction: 'Zahlung prüfen',
    recoveryDescription: 'Öffnen Sie die sichere Zahlungsseite, um Zahlung oder Karte zu prüfen.',
    recoveryUnavailable: 'Diese Aktion ist gerade nicht verfügbar.',
    noSavedPaymentMethod: 'Keine Zahlungsmethode gespeichert',
    savedPaymentMethod: 'Gespeicherte Zahlungsmethode',
    cardFallback: 'Karte',
    cardEnding: ' mit Endziffern {last4}',
    consentedByFallback: 'Teammitglied',
  },
  es: {
    status: { disabled: 'Desactivada', active: 'Activada', paused: 'En pausa', requires_action: 'El pago requiere atención', needs_review: 'En revisión' },
    activeDescription: 'Se aplican el límite de saldo, la cantidad de recarga y el límite mensual guardados.',
    disabledDescription: 'La recarga automática está desactivada para este equipo.',
    pausedForCapDescription: 'El límite mensual no cubre otra recarga. Se restablece el {date}.',
    pausedForCapNoResetDescription: 'El límite mensual no cubre otra recarga ahora.',
    optionLabel: 'Añadir {refill} cuando el saldo baje de {threshold}',
    optionDescription: 'Esta opción define el límite de saldo, la cantidad de recarga y el límite mensual.',
    setupAction: 'Configurar recarga automática',
    setupDescription: 'Revisa y confirma estas condiciones antes de activarla.',
    setupUnavailable: 'Elige una opción disponible y guarda primero un método de pago.',
    updateAction: 'Usar esta opción de recarga',
    updateDescription: 'Cambiar el límite de saldo, la cantidad de recarga y el límite mensual.',
    updateUnavailable: 'No se puede cambiar esta opción ahora. Revisa el método de pago y el consentimiento.',
    consentDescription: 'Tu consentimiento cubre el límite de saldo, la cantidad de recarga y el límite mensual guardados.',
    disableAction: 'Desactivar recarga automática',
    disableDescription: 'Detener futuros cargos automáticos. Los créditos disponibles no cambiarán.',
    disableUnavailable: 'No se puede desactivar la recarga automática ahora.',
    changeCardAction: 'Cambiar tarjeta',
    reviewPaymentAction: 'Revisar pago',
    recoveryDescription: 'Abre la página segura de pago para revisar el pago o la tarjeta.',
    recoveryUnavailable: 'Esta acción no está disponible ahora.',
    noSavedPaymentMethod: 'No hay un método de pago guardado',
    savedPaymentMethod: 'Método de pago guardado',
    cardFallback: 'Tarjeta',
    cardEnding: ' que termina en {last4}',
    consentedByFallback: 'Miembro del equipo',
  },
  fr: {
    status: { disabled: 'Désactivée', active: 'Activée', paused: 'En pause', requires_action: 'Paiement à vérifier', needs_review: 'En cours de vérification' },
    activeDescription: 'Le seuil de solde, le montant de recharge et la limite mensuelle enregistrés s’appliquent.',
    disabledDescription: 'La recharge automatique est désactivée pour cette équipe.',
    pausedForCapDescription: 'La limite mensuelle ne couvre pas une autre recharge. Elle est réinitialisée le {date}.',
    pausedForCapNoResetDescription: 'La limite mensuelle ne couvre pas une autre recharge pour le moment.',
    optionLabel: 'Ajouter {refill} lorsque le solde passe sous {threshold}',
    optionDescription: 'Cette option définit le seuil de solde, le montant de recharge et la limite mensuelle.',
    setupAction: 'Configurer la recharge automatique',
    setupDescription: 'Vérifiez et confirmez ces conditions avant de l’activer.',
    setupUnavailable: 'Choisissez une option disponible et enregistrez d’abord un moyen de paiement.',
    updateAction: 'Utiliser cette option de recharge',
    updateDescription: 'Modifier le seuil de solde, le montant de recharge et la limite mensuelle.',
    updateUnavailable: 'Cette option ne peut pas être modifiée pour le moment. Vérifiez le paiement et le consentement.',
    consentDescription: 'Votre consentement porte sur le seuil de solde, le montant de recharge et la limite mensuelle enregistrés.',
    disableAction: 'Désactiver la recharge automatique',
    disableDescription: 'Arrêter les futurs paiements automatiques. Vos crédits disponibles ne changeront pas.',
    disableUnavailable: 'La recharge automatique ne peut pas être désactivée pour le moment.',
    changeCardAction: 'Changer de carte',
    reviewPaymentAction: 'Vérifier le paiement',
    recoveryDescription: 'Ouvrez la page de paiement sécurisée pour vérifier le paiement ou la carte.',
    recoveryUnavailable: 'Cette action est indisponible pour le moment.',
    noSavedPaymentMethod: 'Aucun moyen de paiement enregistré',
    savedPaymentMethod: 'Moyen de paiement enregistré',
    cardFallback: 'Carte',
    cardEnding: ' se terminant par {last4}',
    consentedByFallback: 'Membre de l’équipe',
  },
  it: {
    status: { disabled: 'Disattivata', active: 'Attiva', paused: 'In pausa', requires_action: 'Pagamento da verificare', needs_review: 'In revisione' },
    activeDescription: 'Si applicano la soglia del saldo, l’importo di ricarica e il limite mensile salvati.',
    disabledDescription: 'La ricarica automatica è disattivata per questo team.',
    pausedForCapDescription: 'Il limite mensile non copre un’altra ricarica. Si azzera il {date}.',
    pausedForCapNoResetDescription: 'Il limite mensile non copre un’altra ricarica al momento.',
    optionLabel: 'Aggiungi {refill} quando il saldo scende sotto {threshold}',
    optionDescription: 'Questa opzione definisce la soglia del saldo, l’importo di ricarica e il limite mensile.',
    setupAction: 'Configura la ricarica automatica',
    setupDescription: 'Controlla e conferma queste condizioni prima di attivarla.',
    setupUnavailable: 'Scegli un’opzione disponibile e salva prima un metodo di pagamento.',
    updateAction: 'Usa questa opzione di ricarica',
    updateDescription: 'Modifica la soglia del saldo, l’importo di ricarica e il limite mensile.',
    updateUnavailable: 'Non è possibile modificare questa opzione ora. Controlla il metodo di pagamento e il consenso.',
    consentDescription: 'Il consenso copre la soglia del saldo, l’importo di ricarica e il limite mensile salvati.',
    disableAction: 'Disattiva la ricarica automatica',
    disableDescription: 'Interrompi i futuri addebiti automatici. I crediti disponibili non cambieranno.',
    disableUnavailable: 'Non è possibile disattivare la ricarica automatica ora.',
    changeCardAction: 'Cambia carta',
    reviewPaymentAction: 'Controlla il pagamento',
    recoveryDescription: 'Apri la pagina sicura di pagamento per controllare il pagamento o la carta.',
    recoveryUnavailable: 'Questa azione non è disponibile ora.',
    noSavedPaymentMethod: 'Nessun metodo di pagamento salvato',
    savedPaymentMethod: 'Metodo di pagamento salvato',
    cardFallback: 'Carta',
    cardEnding: ' che termina con {last4}',
    consentedByFallback: 'Membro del team',
  },
} satisfies BillingLocaleCatalog<BillingCreditAutoTopUpCopy>;

export function billingCreditAutoTopUpCopy(locale?: BillingCustomerLocale): BillingCreditAutoTopUpCopy {
  return billingLocaleText(BILLING_CREDIT_AUTO_TOP_UP_COPY, locale);
}
