import { registerInternalAdminDebugLoginRoutes } from './debug-login.js';
import type { FastifyInstance } from 'fastify';
import { registerInternalAdminLifecycle } from './lifecycle.js';
import { registerInternalAdminNativeApps } from './native-apps.js';

import { registerInternalAdminApiKeyRoutes } from './api-keys.js';
import { registerInternalAdminAppRoutes } from './apps.js';
import { registerInternalAdminBanRoutes } from './bans.js';
import { registerInternalAdminBillingStripeUsageRoute } from './billing-stripe-usage.js';
import { registerInternalAdminBillingContractInvoiceRoutes } from './billing-contract-invoices.js';
import { registerInternalAdminBillingCreditInvoiceTaxPolicyRoutes } from './billing-credit-invoice-tax-policies.js';
import { registerInternalAdminPaidUsageExceptionRoutes } from './billing-paid-usage-exceptions.js';
import { registerInternalAdminBillingRoutes } from './billing.js';
import { registerInternalAdminBillingSeatCapacityRoutes } from './billing-seat-capacity.js';
import { registerInternalAdminLedgerRuntimeKeyRoutes } from './billing-ledger-runtime-keys.js';
import { registerInternalAdminConfigRoute } from './config.js';
import { registerInternalAdminConfidentialDelegationRoutes } from './confidential-delegations.js';
import { registerInternalAdminDomainEmailRoutes } from './domain-email.js';
import { registerInternalAdminDomainJwkRoutes } from './domain-jwks.js';
import { registerInternalAdminDomainSignatureRoutes } from './domain-signatures.js';
import { registerInternalAdminDomainSignatureOperationRoutes } from './domain-signature-operations.js';
import { registerInternalAdminDomainRoutes } from './domains.js';
import { registerInternalAdminIntegrationRequestRoutes } from './integration-requests.js';
import { registerInternalAdminOrganisationRoutes } from './organisations.js';
import { registerInternalAdminReadRoutes } from './read.js';
import { registerInternalAdminSuperuserRoutes } from './superusers.js';
import { registerInternalAdminTeamRoutes } from './teams.js';
import { registerInternalAdminTokenRoute } from './token.js';
import { registerInternalAdminUserRoutes } from './users.js';

export function registerInternalAdminRoutes(app: FastifyInstance): void {
  registerInternalAdminLifecycle(app);
  registerInternalAdminNativeApps(app);
  registerInternalAdminConfigRoute(app);
  registerInternalAdminTokenRoute(app);
  registerInternalAdminDebugLoginRoutes(app);
  registerInternalAdminReadRoutes(app);
  registerInternalAdminOrganisationRoutes(app);
  registerInternalAdminAppRoutes(app);
  registerInternalAdminBanRoutes(app);
  registerInternalAdminBillingRoutes(app);
  registerInternalAdminBillingSeatCapacityRoutes(app);
  registerInternalAdminLedgerRuntimeKeyRoutes(app);
  registerInternalAdminBillingContractInvoiceRoutes(app);
  registerInternalAdminBillingCreditInvoiceTaxPolicyRoutes(app);
  registerInternalAdminPaidUsageExceptionRoutes(app);
  registerInternalAdminBillingStripeUsageRoute(app);
  registerInternalAdminConfidentialDelegationRoutes(app);
  registerInternalAdminApiKeyRoutes(app);
  registerInternalAdminDomainRoutes(app);
  registerInternalAdminDomainEmailRoutes(app);
  registerInternalAdminDomainJwkRoutes(app);
  registerInternalAdminDomainSignatureRoutes(app);
  registerInternalAdminDomainSignatureOperationRoutes(app);
  registerInternalAdminUserRoutes(app);
  registerInternalAdminTeamRoutes(app);
  registerInternalAdminSuperuserRoutes(app);
  registerInternalAdminIntegrationRequestRoutes(app);
}
