export const llmJobGrantsMarkdown = `## Asynchronous SalesNerd research grants

SalesNerd may obtain a finite background-job grant when an owner admits a research job. This is separate from session:broker; it does not add broker scope or create a reusable user credential.

The authenticated SalesNerd backend calls POST /auth/job-grants?config_url=... with its existing domain-hash bearer and a fresh RS256 subject assertion. The assertion audience is <PUBLIC_BASE_URL>/auth/job-grants and its signed job_authorization binds request_id, the parent job_id, product salesnerd, resource https://ledger.unlikeotherai.com, purpose research_job, and integer authorized_until. It also carries the current UOA subject, credential epoch, selected active organisation/team, assertion ID and normal short expiry. The maximum job authorization is seven days; clients should use the bounded lifetime of the admitted job. UOA returns its persisted opaque grant_handle and exact expiry. A lost-response retry with the same request ID and identical signed binding recovers the same handle; changing any binding conflicts. The handle alone never authenticates a request.

For each background operation, the product calls POST /auth/job-grants/:grantHandle/renew?config_url=... with the same domain bearer and exact {request_id,job_id}. UOA rechecks the product mapping, active user/domain role, credential epoch and current organisation/team membership before issuing a Ledger-bound ai.invoke RS256 token. Its job_authorization claim identifies the UOA grant, request, parent job, purpose and expiry. Each access token lasts at most 120 seconds and never beyond the original job authorization. Child Ledger run IDs, tool-call IDs and Water IDs remain separately bound by their existing signed call protocol.

Cancel with POST /auth/job-grants/:grantHandle/revoke?config_url=... and the same exact request/job pair. Revocation is idempotent and serializes with renewal. It does not require current human membership, so cancellation remains possible after access is removed. Renewal does require fresh current authority. Revoked, expired, epoch-stale, unmapped or membership-removed jobs cannot renew. A new generation for the same parent job requires a fresh request ID and assertion, and only the original client, subject, organisation and team may create it after the previous generation is revoked, expired or credential-epoch stale; each grant record remains immutable. A new owner-authorized job is required to change that root scope. DeepWater compute renewal grants retain a reference to the exact parent grant, do not outlive it, and stop renewing/dispatching when it is revoked or expires. A product must persist the encrypted UOA handle before enabling worker dispatch, and must not copy refresh tokens or user profile data into its job store.
`;
