import type { EndpointSchema } from './schema.js';

export const lifecycleEndpoints: EndpointSchema[] = [
  { method: 'POST', path: '/oauth/lifecycle-status/start', auth: 'registered public client_id and exact redirect_uri; rate limited', query: { client_id: 'registered client', redirect_uri: 'exact registered callback' }, body: { email: 'valid email' }, description: 'Begin read-only mailbox proof for native/public OAuth account reasons; same neutral delivery behavior as website proof' },
  { method: 'POST', path: '/oauth/lifecycle-status/verify', auth: 'mailbox code and enrolled TOTP; current registered app revision', query: { client_id: 'same registered client', redirect_uri: 'same exact callback' }, body: { challengeId: 'UUID', code: '6digits', twoFactorCode: '6digits if enrolled' }, description: 'Read reasons only; no session or credential grant; revision change invalidates proof' },
  { method: 'GET', path: '/internal/admin/lifecycle/templates', auth: 'live platform superuser', description: 'List reusable scoped customer-facing disable reasons and revisions' },
  { method: 'POST', path: '/internal/admin/lifecycle/templates', auth: 'live platform superuser', description: 'Create or revise a reason template', body: { id: 'optional existing id', scope: 'USER | ORGANISATION | TEAM', title: '1–120 characters', message: '1–2000 plain-text characters', enabled: 'boolean' } },
  { method: 'GET', path: '/internal/admin/lifecycle/:scope/:id', auth: 'live platform superuser', description: 'Read own lifecycle, customer reason, internal note, template revision and durable deletion job id' },
  { method: 'POST', path: '/internal/admin/lifecycle/:scope/:id', auth: 'live platform superuser', description: 'Disable or reactivate access independently of membership state', body: { status: 'ACTIVE | DISABLED', templateId: 'required for disable', templateRevision: 'required exact revision for disable', internalNote: 'optional administrator-only text, max2000' } },
  { method: 'POST', path: '/internal/admin/lifecycle/:scope/:id/deletion-preview', auth: 'live platform superuser', description: 'Preview team/org cascade, candidate account dependencies, product participants, active financial blockers and restricted evidence', body: { mode: 'RETAIN_REFERENCE | ERASE_REFERENCE' } },
  { method: 'POST', path: '/internal/admin/lifecycle/:scope/:id/delete', auth: 'live platform superuser', description: 'Confirm a current preview and start durable terminal deletion', body: { mode: 'RETAIN_REFERENCE | ERASE_REFERENCE', previewDigest: 'current preview SHA256', confirmation: 'exact preview confirmation string', requestKey: 'UUID reused for retries' } },
  { method: 'GET', path: '/internal/admin/lifecycle/deletion-jobs/:id', auth: 'live platform superuser', description: 'Read durable progress and product acknowledgements' },
  { method: 'POST', path: '/internal/admin/lifecycle/deletion-jobs/:id/retry', auth: 'live platform superuser', description: 'Execute or retry local cleanup once all expected products acknowledge; bounded leased stages commit progress; retry READY to continue; COMPLETE is idempotent' },
  { method: 'GET', path: '/domain/deletion-jobs', auth: 'exact registered domain bearer', query: { domain: 'exact registered product identity' }, description: 'Pull up to100 pending jobs assigned to this ClientDomain, without unrelated PII', response: { data: 'id, revision, scope, targetId, effectiveScope, effectiveTargetId, mode, organisationId, teamIds, accountsToDelete' } },
  { method: 'POST', path: '/domain/deletion-jobs/:id/acknowledge', auth: 'exact registered domain bearer', query: { domain: 'exact registered product identity' }, description: 'Acknowledge exact job revision after committed product cleanup; replay must match outcome', body: { revision: 'positive integer', outcome: 'PURGED | RETAINED_EVIDENCE', retainedEvidence: 'optional max30 {label:1–120chars,count:positive integer,reason:1–500chars}; only for retained outcome, no unrelated PII' } },
  { method: 'GET', path: '/domain/historical-users/:id', auth: 'exact registered domain bearer and prior historical subject association', query: { domain: 'exact registered product identity' }, description: 'Resolve a retained terminal subject as id/deleted:true/name:Deleted user; no email, avatar, credentials or memberships' },
  { method: 'POST', path: '/auth/lifecycle-status/start', auth: 'verified signed product config; rate limited', query: { config_url: 'signed product config URL' }, description: 'Begin mailbox proof for read-only access reasons; generic response even for absent/deleted identity or mail failure', body: { email: 'valid email' }, response: { ok: 'true', challengeId: 'opaque UUID' } },
  { method: 'POST', path: '/auth/lifecycle-status/verify', auth: 'mailbox code and enrolled TOTP; exact config binding', query: { config_url: 'same signed product config URL' }, description: 'Consume proof and return own account and authorized organisation/team access reasons; never an authentication token or internal note', body: { challengeId: 'UUID', code: '6digits', twoFactorCode: '6digits if enrolled' } },
];

export const lifecycleDocumentation = {
  states: ['ACTIVE', 'DISABLED', 'DELETING', 'DELETED'],
  deleted_identity: '{id,deleted:true,name:"Deleted user"}; PII null/omitted. The boolean derives from lifecycle state.',
  deletion_modes: 'RETAIN_REFERENCE retains a non-authenticating subject; ERASE_REFERENCE erases mutable references. Immutable financial/signing evidence can require a restricted identity stub and is explicitly listed.',
  product_delivery: 'Durable pull/ack, exact ClientDomain identity, exact revision, no arbitrary hooks. Missing registered participant authority or pending product acknowledgement blocks completion.',
  access: 'Lifecycle denial has no superuser bypass. Parent disable inherits denial without changing independent child or membership states. Offline product JWT acceptance must use online introspection/revocation or bounded expiry.',
  legacy_delete: 'Existing direct organisation/team DELETE routes return409 ENTITY_DELETION_WORKFLOW_REQUIRED; use platform-admin preview/confirmation/job flow.',
};
