import type { EndpointSchema } from './schema.js';

export const automaticMembershipEndpoints: EndpointSchema[] = [
  { method: 'POST', path: '/org/automatic-membership/attestations', description: 'Attest a UOA subject has a currently verified exact email domain.', auth: 'Dedicated automatic-membership app key for the Nessie service only', body: { uoaSub: 'UOA stable subject', domain: 'exact ASCII domain' }, response: { '200': 'short-lived UOA attestation', '204': 'no current verified matching identity' } },
  { method: 'GET', path: '/org/automatic-membership/organisations/:orgId/teams', description: 'List UOA-owned team targets after direct Nessie service-access scope check.', auth: 'Dedicated automatic-membership app key' },
  { method: 'POST', path: '/org/automatic-membership/organisations/:orgId/authorizations', description: 'Recheck a requester is an organisation owner/admin or administrator of every named team.', auth: 'Dedicated automatic-membership app key' },
  { method: 'GET', path: '/org/automatic-membership/organisations/:orgId/subjects', description: 'Cursor-page stable UOA subjects with a currently verified exact matching email; no email is returned.', auth: 'Dedicated automatic-membership app key', query: { domain: 'exact ASCII domain', snapshot_id: 'required after the first page', cursor: 'opaque cursor', limit: '1-100' } },
  { method: 'PUT', path: '/org/automatic-membership/organisations/:orgId/rules/:ruleId/fence', description: 'Install or cancel the UOA-verified current rule generation fence. Older generations are rejected.', auth: 'Dedicated automatic-membership app key', body: { generation: 'positive generation', fence_token: 'opaque current fence', active: 'whether grants are permitted' } },
  { method: 'POST', path: '/org/automatic-membership/organisations/:orgId/teams/:teamId/grants', description: 'Idempotently grant only normal organisation/team member access after UOA validates the persisted rule fence and the subject’s current verified exact domain. Existing stronger roles are retained.', auth: 'Dedicated automatic-membership app key', body: { subject: 'UOA stable subject', domain: 'exact ASCII verified domain', idempotency_key: 'caller idempotency key', rule_id: 'Nessie rule id', rule_generation: 'positive generation fence', fence_token: 'current persisted fence' } },
  { method: 'GET', path: '/org/automatic-membership/operations/:operationId', description: 'Read a durable automatic-membership operation status.', auth: 'Dedicated automatic-membership app key' },
];
