import type { EndpointSchema } from './schema.js';

const auth = 'verified config_url and the calling product’s existing domain-hash bearer';

export const salesResearchJobGrantEndpoints: EndpointSchema[] = [
  {
    method: 'POST', path: '/auth/job-grants',
    description: 'Create or recover one finite SalesNerd research-job authority from a fresh signed subject assertion.',
    auth, query: { config_url: 'signed app config whose domain matches the authenticated bearer' },
    body: {
      request_id: 'UUID durably generated by the product before first issuance; exact retries recover the same UOA grant.',
      subject_token: 'Fresh source-config RS256 assertion, max 60 seconds, aud=PUBLIC_BASE_URL+/auth/job-grants, with active org/team, sub/tv/jti and signed job_authorization tuple.',
      subject_token_type: 'urn:ietf:params:oauth:token-type:jwt',
    },
    response: {
      grant_handle: 'UOA-generated opaque UUID; useful only with the same authenticated product domain credential.',
      expires_at: 'Exact signed authorized_until as RFC3339; never sliding or extended on replay.',
      '[status]': '201 first commit; 200 exact response-loss recovery.',
    },
    notes: 'Only SalesNerd ai.invoke to the exact Ledger resource is supported. The signed job_authorization claim binds request_id, parent job_id, product, resource, purpose=research_job and authorized_until (integer epoch seconds, at most 7 days). A new request ID can create another immutable grant generation only for the same original client/subject/org/team after the prior generation is expired, revoked or credential-epoch stale; an active grant in the same epoch is reused.',
  },
  {
    method: 'POST', path: '/auth/job-grants/:grantHandle/renew',
    description: 'Renew one short-lived, exact-resource AI invocation token for an active originally authorized SalesNerd job.',
    auth, query: { config_url: 'same signed app config and domain credential used to issue the grant' },
    body: { request_id: 'original grant request UUID', job_id: 'exact admitted parent research_job ID' },
    response: {
      access_token: 'UOA RS256 token for https://ledger.unlikeotherai.com, product salesnerd, exact ai.invoke and original active team; max 120 seconds and never beyond grant expiry.',
      token_type: 'Bearer', expires_in: 'seconds', scope: 'ai.invoke',
    },
    notes: 'Every renewal rechecks current product mapping, source role, active identity and team membership, credential epoch, grant expiry and revocation. The token carries the signed parent job grant identity; child Ledger/Water lineage remains separately bound.',
  },
  {
    method: 'POST', path: '/auth/job-grants/:grantHandle/revoke',
    description: 'Revoke one exact SalesNerd research-job grant; exact repeats are idempotent.',
    auth, query: { config_url: 'same signed app config and domain credential used to issue the grant' },
    body: { request_id: 'original grant request UUID', job_id: 'exact admitted parent research_job ID' },
    response: { revoked: 'true' },
    notes: 'Revoke serializes with renew and does not require current human membership, so a cancelled job can be closed after the owner loses access. Grant identifiers alone never authenticate a request.',
  },
];
