import type { EndpointSchema } from './schema.js';

export const automaticMembershipEndpoints: EndpointSchema[] = [
  { method: 'POST', path: '/org/automatic-membership/attestations', description: 'Attest a UOA subject has a currently verified exact email domain, scoped to an organisation with current service access.', auth: 'Dedicated automatic-membership uoa_app_ credential for the Nessie service only', body: { uoaSub: 'UOA stable subject', org_id: 'exact UOA organisation id', domain: 'exact ASCII domain' }, response: { '200': 'short-lived UOA attestation', '204': 'no current verified matching identity' } },
  { method: 'GET', path: '/org/automatic-membership/organisations/:orgId/teams', description: 'List UOA-owned team targets after direct Nessie service-access scope check.', auth: 'Dedicated automatic-membership app key' },
  { method: 'POST', path: '/org/automatic-membership/organisations/:orgId/authorizations', description: 'Recheck a requester against one exact scope. organisation requires active UOA org owner/admin; team requires active owner/admin on the named UOA team.', auth: 'Dedicated automatic-membership app key', body: { subject: 'UOA stable subject', scope: 'organisation | organization | team (new)', team_id: 'required for team scope', team_ids: 'legacy compatible array; omitted for exact scope' }, response: { 200: '{ allowed, authorization? }; authorization echoes the subject, exact org/team and scope that UOA just checked' } },
  { method: 'GET', path: '/org/automatic-membership/organisations/:orgId/subjects', description: 'Cursor-page stable UOA subjects with a currently verified exact matching email; no email is returned. Cursor is opaque, snapshot-bound and single-use; restart without snapshot_id/cursor after either snapshot error.', auth: 'Dedicated automatic-membership app key', query: { domain: 'exact ASCII domain', snapshot_id: 'required after the first page', cursor: 'opaque cursor', limit: '1-100' } },
  { method: 'PUT', path: '/org/automatic-membership/organisations/:orgId/rules/:ruleId/fence', description: 'Install or cancel the UOA-verified current rule generation fence. Generation and lifecycle_revision are monotonic; older or conflicting revisions are rejected.', auth: 'Dedicated automatic-membership app key', body: { generation: 'positive generation', lifecycle_revision: 'non-negative lifecycle revision, default 0 for rollout compatibility', fence_token: 'opaque current fence', active: 'whether grants are permitted' } },
  { method: 'POST', path: '/org/automatic-membership/organisations/:orgId/teams/:teamId/grants', description: 'Idempotently create only absent normal organisation/team member records after UOA validates the locked persisted fence and the subject’s current verified exact domain. Existing inactive memberships are skipped, never reactivated; stronger active roles are retained.', auth: 'Dedicated automatic-membership app key', body: { subject: 'UOA stable subject', domain: 'exact ASCII verified domain', idempotency_key: 'caller idempotency key', rule_id: 'Nessie rule id', rule_generation: 'positive generation fence', lifecycle_revision: 'non-negative lifecycle revision, default 0', fence_token: 'current persisted fence' } },
  { method: 'GET', path: '/org/automatic-membership/operations/:operationId', description: 'Read a durable automatic-membership operation status.', auth: 'Dedicated automatic-membership app key' },
];
