import type { EndpointSchema } from './schema.js';
const base = '/internal/admin/billing/sms-policies';
const auth = 'Current ADMIN_AUTH_DOMAIN SUPERUSER bearer; acceptance rechecks ACTIVE identity and credential epoch under billing administrator authority locks.';
export const internalAdminSmsEndpoints: EndpointSchema[] = [
  { method: 'GET', path: `${base}/liabilities`, auth, description: 'Page original inbound pending/uncollected/reconciliation receipts or outbound dispatching/uncertain/reconciliation holds.',
    query: { kind: 'inbound | outbound (required)', cursor: 'optional last receipt/reservation ID' },
    response: { liabilities: '100 exact resource/allocation/org/team/account/message/dispatch bindings with customer credits; unknown credits remain null', next_cursor: 'next cursor or null' },
    notes: 'No raw provider costs. Reviewing unknown or above-bound liability does not release holds, waive liability, debit credits or authorize a resend.' },
  { method: 'POST', path: `${base}/recovery/:resourceId/verify-refund`, auth,
    description: 'Verify already-existing full original Stripe cash refunds and a canceled subscription, then record immutable resource completion.',
    body: { subscription_id: 'exact original local subscription', refund_ids: '1–20 distinct existing re_ identifiers',
      reason: '8–500 character operator reason', verify_existing_refunds: 'true' },
    response: { resource_id: 'exact number resource', state: 'ended after complete verified evidence', evidence_digest: 'immutable SHA-256', refunded_at: 'source balance transaction time' },
    notes: 'Reads Stripe only; never creates a refund or changes a subscription. Rechecks exact account/mode/resource/org/offer/subscription/invoice/cash/charge/refund/currency/full amount and canceled subscription; source-bound balance movement required. Partial, pending, foreign or changed evidence stays unresolved. Locked operator and resource recheck precede completion and audit. Exact retry is idempotent.' },
  { method: 'GET', path: `${base}/recovery`, auth, description: 'Read ending, recovery-required and refund-required number resources in bounded pages.',
    query: { cursor: 'optional exact last resource ID from previous page' },
    response: { resources: '100 private resource/org/product/phone/state/reason/time records', next_cursor: 'next resource cursor or null' } },
  { method: 'GET', path: `${base}/recovery/:resourceId`, auth, description: 'Review exact original customer quote and Stripe payment references for a number resource.',
    response: { resource: 'resource and provider binding; final customer quote; exact Stripe account/mode/subscription/initial invoice references',
      refund_action_available: 'whether original paid references permit presenting the separate refund evidence form', operator_next_step: 'explicit unresolved recovery instruction' },
    notes: 'No raw provider quote costs, markup or financial side effect. Reading never infers refund completion; only the explicit verified existing-refund action can end refund_required.' },
  { method: 'GET', path: base, auth, description: 'Read bounded immutable SMS policy acceptance history (private operator evidence).',
    response: { fx: 'latest 50 accepted FX snapshots', routes: 'latest 100 accepted dimensional fee policies' } },
  { method: 'POST', path: `${base}/fx/preview`, auth, description: 'Refresh fixed ECB daily XML or validate its imported XML; no acceptance write.',
    body: { xml: 'optional bounded ECB daily XML; absent fetches the fixed source without redirects' },
    response: { evidence: 'policy/source/SHA-256/rate date/observed time/expiry/USD-per-EUR exact decimal',
      preview_token: 'operator-and-epoch-bound signed five-minute review', preview_expires_at: 'ISO UTC' } },
  { method: 'POST', path: `${base}/fx/accept`, auth, description: 'Explicitly accept the reviewed informational reference conversion as immutable commercial evidence.',
    body: { preview_token: 'exact fx preview', policy_understood: 'true', acceptance_reason: '8–500 characters' },
    response: { policy: 'immutable accepted evidence plus subject/time/reason' },
    notes: 'Source-date seven-day expiry cannot be extended by refresh or retry; altered, wrong-operator, expired or prior-epoch previews are refused.' },
  { method: 'POST', path: `${base}/routes/preview`, auth, description: 'Validate and hash a documented complete conservative route-fee bound for review.',
    body: { account_sid: 'exact AC SID', country: 'uppercase ISO country', direction: 'inbound | outbound',
      currency: 'USD | EUR', additional_per_segment: 'nonnegative Decimal(38,18) string',
      additional_per_message: 'nonnegative Decimal(38,18) string', source: '8–500 character evidence reference',
      evidence: '20–32000 character fee document/explanation', expires_at: 'future source-supported ISO timestamp' },
    response: { evidence: 'exact dimensions, bounds, source, hash and expiry', preview_token: 'signed five-minute review', preview_expires_at: 'ISO UTC' } },
  { method: 'POST', path: `${base}/routes/accept`, auth, description: 'Append reviewed private fee evidence after explicit completeness acceptance.',
    body: { preview_token: 'exact route preview', policy_understood: 'true', complete_segment_bound: 'true',
      complete_message_bound: 'true', acceptance_reason: '8–500 characters' },
    response: { policy: 'immutable dimensional policy plus subject/time/reason' },
    notes: 'Zero fees require documented supporting evidence; absence from Pricing API never proves zero. No provider or financial action. Preserve original source in the operator evidence archive.' },
];
